---

#######################
# Setup infrastructure
#######################

- hosts: etcd
  roles:
    - common
    - etcd

- hosts: controller
  roles:
    - common
    - controller

- hosts: worker
  roles:
    - common
    - worker
